local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 3.0 
  publish_frequency: 3.0
  transform_tolerance: 1.0 

  static_map: false
  rolling_window: true

  width: 3.0
  height: 3.0

  cost_scaling_factor: 2.25
  inflation_radius: 0.45

  plugins:
  - {name: obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
