# obstacle_range: 5.0
# raytrace_range: 10.0
footprint: [[-0.38, -0.165], [-0.38, 0.165], [0.35, 0.165], [0.35, -0.165]]

transform_tolerance: 1.0
resolution: 0.05 

# static_map_layer:
#     map_topic: map
#     subscribe_to_updates: true

# obstacles_layer:
#   observation_sources: laser_scan
#   laser_scan: {sensor_frame: laser, data_type: LaserScan, topic: scan,
#   obstacle_range: 5.0, raytrace_range: 7.0, marking: true, clearing: true}

3d_obstacles_layer: 
  observation_sources: depth
  depth: {sensor_frame: livox360_sensor, data_type: PointCloud2, topic: livox/lidar,
     min_obstacle_height: 0.08, max_obstacle_height: 0.85, 
     obstacle_range: 3.5, raytrace_range: 4.0, marking: true, clearing: true}

fall_obstacles_layer: 
  observation_sources: depth
  depth: {sensor_frame: livox360_sensor, data_type: PointCloud2, topic: livox/lidar,
     min_obstacle_height: -1.5, max_obstacle_height: -0.25, 
     obstacle_range: 3.5, raytrace_range: 4.0, marking: true, clearing: true}

# inflation_layer:
#     inflation_radius: 2.0

# plugins:
#   - {name: static_map_layer,    type: "costmap_2d::StaticLayer"}
#   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
#   - {name: obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
#   - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
